version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smartlms_mysql
    environment:
      MYSQL_DATABASE: lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lms_network
    restart: always

  backend:
    build:
      context: ./backend
    container_name: smartlms_backend
    environment:
      DB_NAME: lms_db
      DB_USER: lms_user
      DB_PASSWORD: lms_pass
      DB_HOST: mysql
      SECRET_KEY: prod-secret-key
      DEBUG: 'False'
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - lms_network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: smartlms_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - lms_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: smartlms_nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - frontend
      - backend
    networks:
      - lms_network
    restart: always

networks:
  lms_network:
    driver: bridge

volumes:
  mysql_data:
  media_volume:
